version: 2

jobs:
  init:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init
          command: |
            terraform init -input=false
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform plan
          command: |
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform apply
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  #plan-destroy:
  #  docker:
  #    - image: hashicorp/terraform:light
  #  steps:
  #    - attach_workspace:
  #        at: .
  #    - run:
  #        name: terraform create destroy plan
  #        command: |
  #          terraform plan -destroy -out tfdestroy
  #    - persist_to_workspace:
  #        root: .
  #        paths:
  #          - .

  #destroy:
  #  docker:
  #    - image: hashicorp/terraform:light
  #  steps:
  #    - attach_workspace:
  #        at: .
  #    - run:
  #        name: terraform destroy
  #        command: |
  #          terraform apply -auto-approve tfdestroy
  
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - init
      - hold-plan:
          type: approval
          requires:
            - init
      - plan:
          requires:
            - hold-plan
      - hold-apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold-apply
            
      #- plan-destroy:
      #    requires:
      #      - apply
      #- hold-destroy:
      #    type: approval
      #    requires:
      #      - plan-destroy
      #- destroy:
      #    requires:
      #      - hold-destroy